package com.example.logiratha.model

import android.os.Parcelable
import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.parcelize.Parcelize

@Parcelize
@Entity(tableName = "userinfo") // User Entity represents a table within the database.
data class UserInfo(
    @PrimaryKey(autoGenerate = true)
    val userId: Int, // <- 'id' is the primary key which will be autogenerated by the Room library.
    val userMobileNo: String,
    val userName: String,
    val userPassword: String,
    val userEmail: String,
    val isRegistered: Boolean
): Parcelable